# Generated by Django 5.1.1 on 2024-09-12 03:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stadium',
            index=models.Index(fields=['name'], name='stadium_name_idx'),
        ),
    ]
