# Generated by Django 5.1.1 on 2024-09-12 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0003_stadium_stadium_name_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stadiums.stadium'),
        ),
    ]
